### ISSUE TITLE
ImportError: No module named 'package_control'

### ISSUE THREAD

**Issue by jasalazar** [wbond/package_control#888]
Sublime Text 3 throws the following:

```
reloading plugin Package Control.Package Control
reloading plugin Package Control.bootstrap
found 3 files for base name Main.sublime-menu
Package Control: Downloading bootstrapped dependency ssl-linux
reloading Packages/User/Package Control.sublime-settings
Package Control: Installing 2 missing dependencies
Package Control: Successfully downloaded bootstraped dependency ssl-linux
Exception in thread Thread-1:
Traceback (most recent call last):
  File "./threading.py", line 901, in _bootstrap_inner
  File "./threading.py", line 858, in run
  File "package_control.bootstrap in /home/jsalazar/.config/sublime-text-3/Installed Packages/Package Control.sublime-package", line 142, in bootstrap_dependency
  File "package_control.loader in /home/jsalazar/.config/sublime-text-3/Installed Packages/Package Control.sublime-package", line 191, in add
  File "/home/jsalazar/.config/sublime-text-3/Installed Packages/0_package_control_loader.sublime-package/01-ssl-linux.py", line 6, in <module>
ImportError: No module named 'package_control'

Package Control: Error downloading channel. curl: (56) SSL read: error:00000000:lib(0):func(0):reason(0), errno 104 downloading https://packagecontrol.io/channel_v3.json.
Package Control: The dependency specified, bz2, is not available
Package Control: Error downloading channel. curl: (56) SSL read: error:00000000:lib(0):func(0):reason(0), errno 110 downloading https://packagecontrol.io/channel_v3.json.
Package Control: The dependency specified, ssl-linux, is not available
Package Control: Error downloading channel. curl: (35) Unknown SSL protocol error in connection to packagecontrol.io:443 downloading https://packagecontrol.io/channel_v3.json.
Package Control: No updated packages
```

I am running Ubuntu 14.04.2 on a AMD 64 bits.

Didn't found anything online about it.

**Comment by wbond** [comment]
Please turn on the `debug` flag, as instructed at https://github.com/wbond/package_control/blob/master/contributing.md and create a full debug log.

**Comment by wbond** [comment]
@jasalazar bump

**Comment by wbond** [comment]
I believe this should be fixed by be92f50804c62e747585ec6b025e0e07acbed830. It is available in the master branch here on GitHub, or will be part of the 3.1.0 release.

**Comment by kostrovart** [comment]
Actually, I have _version: 3103 linux x32_, but this bug still here :-(

**Comment by wbond** [comment]
@kostrovart Try following the directions at https://packagecontrol.io/docs/troubleshooting#Purging_and_Reinstalling.

**Comment by kostrovart** [comment]
Excellent! But, I just removed "Package Control" from the "ignored_packages" and reload Sublime. And it helped! "Purging and Reinstalling" wasn't needed in this time!
