### ISSUE TITLE
Selecting a package from List Packages results in error

### ISSUE THREAD

**Issue by tedmiston** [wbond/package_control#923]
When selecting a package from `List Packages` on Mac OS X, I get the error dialog:

> The application can't be found.

It seems to occur with every package.

I'm using v3.0.1 with Sublime 3083.

Would be nice to know if others can reproduce.

*Update*: This seems to occur only with packages installed to the `Installed Packages` directory, but not the `Packages` directory.  I'm not too keen on what the difference is, but of the packages I have installed 22 are in the former (as `*.sublime-package` files) and 9 in the latter (as directories).

**Comment by wbond** [comment]
Good catch about the `.sublime-package` file distinction. It worked for me the first few times since most of my packages are unpacked. I'll have it open the `Installed Packages/` dir for packed packages.

**Comment by davidhq** [comment]
+1

**Comment by JMayfield** [comment]
Same problem here!

**Comment by wbond** [comment]
This is fixed by 8366aa101ec69cb512948184f4cdb732444fef31

**Comment by davidhq** [comment]
I just upgraded Package Control (by pasting this code: https://packagecontrol.io/installation) into console (is that how yo do an upgrade?) .. and the problem from this ticket still persists... so the fix is not yet in the build?

**Comment by wbond** [comment]
Correct, the commit with the fix has not yet been part of a stable release. You will have to use git to clone the master branch to test it out.

**Comment by davidhq** [comment]
I'll wait.. any ETA? Also could you possibly comment here when it make to stable relase?

**Comment by wbond** [comment]
ETA – probably within the next few days. I should be making a new beta release of 3.1.0 in the next day or so, and I will give it a little for bug reports to come in.

For the 3.1.0 release, you should see an upgrade notice inside of Sublime Text.

**Comment by davidhq** [comment]
ok, thank you....

**Comment by tedmiston** [comment]
Thanks for the fix!
